/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MyFirstContractContract } from "./MyFirstContract";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "MyFirstContract"): MyFirstContractContract;
    }
  }
}

export {
  MyFirstContractContract,
  MyFirstContractInstance,
} from "./MyFirstContract";
