/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { BankContract } from "./Bank";
import { MyFirstContractContract } from "./MyFirstContract";
import { RegulatorContract } from "./Regulator";
import { TestThrowsContract } from "./TestThrows";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Bank"): BankContract;
      require(name: "MyFirstContract"): MyFirstContractContract;
      require(name: "Regulator"): RegulatorContract;
      require(name: "TestThrows"): TestThrowsContract;
    }
  }
}

export { BankContract, BankInstance } from "./Bank";
export {
  MyFirstContractContract,
  MyFirstContractInstance,
} from "./MyFirstContract";
export { RegulatorContract, RegulatorInstance } from "./Regulator";
export { TestThrowsContract, TestThrowsInstance } from "./TestThrows";
