/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TestThrowsContract
  extends Truffle.Contract<TestThrowsInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TestThrowsInstance>;
}

type AllEvents = never;

export interface TestThrowsInstance extends Truffle.ContractInstance {
  testAssert(txDetails?: Truffle.TransactionDetails): Promise<void>;

  testRequire(txDetails?: Truffle.TransactionDetails): Promise<void>;

  testRevert(txDetails?: Truffle.TransactionDetails): Promise<void>;

  methods: {
    testAssert(txDetails?: Truffle.TransactionDetails): Promise<void>;

    testRequire(txDetails?: Truffle.TransactionDetails): Promise<void>;

    testRevert(txDetails?: Truffle.TransactionDetails): Promise<void>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
