/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { TransactionContract } from "./Transaction";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Transaction"): TransactionContract;
    }
  }
}

export { TransactionContract, TransactionInstance } from "./Transaction";
