/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { IntExtendedContract } from "./IntExtended";
import { TestLibraryContract } from "./TestLibrary";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "IntExtended"): IntExtendedContract;
      require(name: "TestLibrary"): TestLibraryContract;
    }
  }
}

export { IntExtendedContract, IntExtendedInstance } from "./IntExtended";
export { TestLibraryContract, TestLibraryInstance } from "./TestLibrary";
