/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IntExtendedContract
  extends Truffle.Contract<IntExtendedInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IntExtendedInstance>;
}

type AllEvents = never;

export interface IntExtendedInstance extends Truffle.ContractInstance {
  increment(
    _self: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  decrement(
    _self: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  incrementByValue(
    _self: number | BN | string,
    _value: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  decrementByValue(
    _self: number | BN | string,
    _value: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    increment(
      _self: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    decrement(
      _self: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    incrementByValue(
      _self: number | BN | string,
      _value: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    decrementByValue(
      _self: number | BN | string,
      _value: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
