/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface TestLibraryContract
  extends Truffle.Contract<TestLibraryInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<TestLibraryInstance>;
}

type AllEvents = never;

export interface TestLibraryInstance extends Truffle.ContractInstance {
  testIncrement(
    _base: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  testDecrement(
    _base: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  testIncrementByValue(
    _base: number | BN | string,
    _value: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  testDecrementByValue(
    _base: number | BN | string,
    _value: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  methods: {
    testIncrement(
      _base: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    testDecrement(
      _base: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    testIncrementByValue(
      _base: number | BN | string,
      _value: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    testDecrementByValue(
      _base: number | BN | string,
      _value: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
